
package com.github.yourarj.e_filing.gov.bulk_pan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BulkPanService", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BulkPanService {


    /**
     * 
     * @param ditRequest
     * @return
     *     returns bulk_pan.BulkPanResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
    @RequestWrapper(localName = "uploadBulkPan", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", className = "bulk_pan.UploadBulkPan")
    @ResponseWrapper(localName = "uploadBulkPanResponse", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", className = "bulk_pan.UploadBulkPanResponse")
    public BulkPanResponse uploadBulkPan(
            @WebParam(name = "DitRequest", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
                    BulkPanRequest ditRequest);

}
