
package com.github.yourarj.e_filing.gov.itrv_by_tokenno;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetItrVByTokenNoService", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", wsdlLocation = "https://services.incometaxindiaefiling.gov.in/e-FilingSecWS/ditsecws/GetItrVByTokenNoService?wsdl")
public class GetItrVByTokenNoService_Service
    extends Service
{

    private final static URL GETITRVBYTOKENNOSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETITRVBYTOKENNOSERVICE_EXCEPTION;
    private final static QName GETITRVBYTOKENNOSERVICE_QNAME = new QName("http://incometaxindiaefiling.gov.in/ditsecws", "GetItrVByTokenNoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://services.incometaxindiaefiling.gov.in/e-FilingSecWS/ditsecws/GetItrVByTokenNoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETITRVBYTOKENNOSERVICE_WSDL_LOCATION = url;
        GETITRVBYTOKENNOSERVICE_EXCEPTION = e;
    }

    public GetItrVByTokenNoService_Service() {
        super(__getWsdlLocation(), GETITRVBYTOKENNOSERVICE_QNAME);
    }

    public GetItrVByTokenNoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETITRVBYTOKENNOSERVICE_QNAME, features);
    }

    public GetItrVByTokenNoService_Service(URL wsdlLocation) {
        super(wsdlLocation, GETITRVBYTOKENNOSERVICE_QNAME);
    }

    public GetItrVByTokenNoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETITRVBYTOKENNOSERVICE_QNAME, features);
    }

    public GetItrVByTokenNoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetItrVByTokenNoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetItrVByTokenNoService
     */
    @WebEndpoint(name = "GetItrVByTokenNoServicePort")
    public GetItrVByTokenNoService getGetItrVByTokenNoServicePort() {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/ditsecws", "GetItrVByTokenNoServicePort"), GetItrVByTokenNoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetItrVByTokenNoService
     */
    @WebEndpoint(name = "GetItrVByTokenNoServicePort")
    public GetItrVByTokenNoService getGetItrVByTokenNoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/ditsecws", "GetItrVByTokenNoServicePort"), GetItrVByTokenNoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETITRVBYTOKENNOSERVICE_EXCEPTION!= null) {
            throw GETITRVBYTOKENNOSERVICE_EXCEPTION;
        }
        return GETITRVBYTOKENNOSERVICE_WSDL_LOCATION;
    }

}
