
package com.github.yourarj.e_filing.gov.itrv_by_ackno;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetItrVByAckNoService", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", wsdlLocation = "https://services.incometaxindiaefiling.gov.in/e-FilingSecWS/ditsecws/GetItrVByAckNoService?wsdl")
public class GetItrVByAckNoService_Service
    extends Service
{

    private final static URL GETITRVBYACKNOSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETITRVBYACKNOSERVICE_EXCEPTION;
    private final static QName GETITRVBYACKNOSERVICE_QNAME = new QName("http://incometaxindiaefiling.gov.in/ditsecws", "GetItrVByAckNoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://services.incometaxindiaefiling.gov.in/e-FilingSecWS/ditsecws/GetItrVByAckNoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETITRVBYACKNOSERVICE_WSDL_LOCATION = url;
        GETITRVBYACKNOSERVICE_EXCEPTION = e;
    }

    public GetItrVByAckNoService_Service() {
        super(__getWsdlLocation(), GETITRVBYACKNOSERVICE_QNAME);
    }

    public GetItrVByAckNoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETITRVBYACKNOSERVICE_QNAME, features);
    }

    public GetItrVByAckNoService_Service(URL wsdlLocation) {
        super(wsdlLocation, GETITRVBYACKNOSERVICE_QNAME);
    }

    public GetItrVByAckNoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETITRVBYACKNOSERVICE_QNAME, features);
    }

    public GetItrVByAckNoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetItrVByAckNoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetItrVByAckNoService
     */
    @WebEndpoint(name = "GetItrVByAckNoServicePort")
    public GetItrVByAckNoService getGetItrVByAckNoServicePort() {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/ditsecws", "GetItrVByAckNoServicePort"), GetItrVByAckNoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetItrVByAckNoService
     */
    @WebEndpoint(name = "GetItrVByAckNoServicePort")
    public GetItrVByAckNoService getGetItrVByAckNoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/ditsecws", "GetItrVByAckNoServicePort"), GetItrVByAckNoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETITRVBYACKNOSERVICE_EXCEPTION!= null) {
            throw GETITRVBYACKNOSERVICE_EXCEPTION;
        }
        return GETITRVBYACKNOSERVICE_WSDL_LOCATION;
    }

}
