
package com.github.yourarj.e_filing.gov.bulk_itr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BulkItrService", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BulkItrService {


    /**
     * 
     * @param ditRequest
     * @return
     *     returns bulk_itr.BulkItrResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
    @RequestWrapper(localName = "uploadBulkItr", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", className = "bulk_itr.UploadBulkItr")
    @ResponseWrapper(localName = "uploadBulkItrResponse", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", className = "bulk_itr.UploadBulkItrResponse")
    public BulkItrResponse uploadBulkItr(
            @WebParam(name = "DitRequest", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
                    BulkItrRequest ditRequest);

}
