
package com.github.yourarj.e_filing.gov.return_status;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReturnStatusService", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReturnStatusService {


    /**
     * 
     * @param ditRequest
     * @return
     *     returns return_status.ReturnStatusResponse
     */
    @WebMethod
    @WebResult(name = "DitResponse", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
    @RequestWrapper(localName = "getReturnStatus", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", className = "return_status.GetReturnStatus")
    @ResponseWrapper(localName = "getReturnStatusResponse", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", className = "return_status.GetReturnStatusResponse")
    public ReturnStatusResponse getReturnStatus(
            @WebParam(name = "DitRequest", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
                    ReturnStatusRequest ditRequest);

}
