
package com.github.yourarj.e_filing.gov.return_status;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReturnStatusService", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", wsdlLocation = "https://services.incometaxindiaefiling.gov.in/e-FilingSecWS/ditsecws/ReturnStatusService?wsdl")
public class ReturnStatusService_Service
    extends Service
{

    private final static URL RETURNSTATUSSERVICE_WSDL_LOCATION;
    private final static WebServiceException RETURNSTATUSSERVICE_EXCEPTION;
    private final static QName RETURNSTATUSSERVICE_QNAME = new QName("http://incometaxindiaefiling.gov.in/ditsecws", "ReturnStatusService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://services.incometaxindiaefiling.gov.in/e-FilingSecWS/ditsecws/ReturnStatusService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RETURNSTATUSSERVICE_WSDL_LOCATION = url;
        RETURNSTATUSSERVICE_EXCEPTION = e;
    }

    public ReturnStatusService_Service() {
        super(__getWsdlLocation(), RETURNSTATUSSERVICE_QNAME);
    }

    public ReturnStatusService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RETURNSTATUSSERVICE_QNAME, features);
    }

    public ReturnStatusService_Service(URL wsdlLocation) {
        super(wsdlLocation, RETURNSTATUSSERVICE_QNAME);
    }

    public ReturnStatusService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RETURNSTATUSSERVICE_QNAME, features);
    }

    public ReturnStatusService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReturnStatusService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReturnStatusService
     */
    @WebEndpoint(name = "ReturnStatusServicePort")
    public ReturnStatusService getReturnStatusServicePort() {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/ditsecws", "ReturnStatusServicePort"), ReturnStatusService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReturnStatusService
     */
    @WebEndpoint(name = "ReturnStatusServicePort")
    public ReturnStatusService getReturnStatusServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/ditsecws", "ReturnStatusServicePort"), ReturnStatusService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RETURNSTATUSSERVICE_EXCEPTION!= null) {
            throw RETURNSTATUSSERVICE_EXCEPTION;
        }
        return RETURNSTATUSSERVICE_WSDL_LOCATION;
    }

}
