
package com.github.yourarj.e_filing.gov.evc_thru_bank_atm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BankAtmGenEvcService", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankAtmGenEvcService {


    /**
     * 
     * @param ditRequest
     * @return
     *     returns evc_thru_bank_atm.BankAtmGenEvcResponse
     */
    @WebMethod
    @WebResult(name = "DitResponse", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
    @RequestWrapper(localName = "getBankAtmGenEvcDetails", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", className = "evc_thru_bank_atm.GetBankAtmGenEvcDetails")
    @ResponseWrapper(localName = "getBankAtmGenEvcDetailsResponse", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", className = "evc_thru_bank_atm.GetBankAtmGenEvcDetailsResponse")
    public BankAtmGenEvcResponse getBankAtmGenEvcDetails(
            @WebParam(name = "DitRequest", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws")
                    BankAtmGenEvcRequest ditRequest);

}
