
package com.github.yourarj.e_filing.gov.evc_thru_bank_atm;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BankAtmGenEvcService", targetNamespace = "http://incometaxindiaefiling.gov.in/ditsecws", wsdlLocation = "https://services.incometaxindiaefiling.gov.in/e-FilingSecWS/ditsecws/BankAtmGenEvcService?wsdl")
public class BankAtmGenEvcService_Service
    extends Service
{

    private final static URL BANKATMGENEVCSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(BankAtmGenEvcService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = BankAtmGenEvcService_Service.class.getResource(".");
            url = new URL(baseUrl, "https://services.incometaxindiaefiling.gov.in/e-FilingSecWS/ditsecws/BankAtmGenEvcService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://services.incometaxindiaefiling.gov.in/e-FilingSecWS/ditsecws/BankAtmGenEvcService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BANKATMGENEVCSERVICE_WSDL_LOCATION = url;
    }

    public BankAtmGenEvcService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankAtmGenEvcService_Service() {
        super(BANKATMGENEVCSERVICE_WSDL_LOCATION, new QName("http://incometaxindiaefiling.gov.in/ditsecws", "BankAtmGenEvcService"));
    }

    /**
     * 
     * @return
     *     returns BankAtmGenEvcService
     */
    @WebEndpoint(name = "BankAtmGenEvcServicePort")
    public BankAtmGenEvcService getBankAtmGenEvcServicePort() {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/ditsecws", "BankAtmGenEvcServicePort"), BankAtmGenEvcService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankAtmGenEvcService
     */
    @WebEndpoint(name = "BankAtmGenEvcServicePort")
    public BankAtmGenEvcService getBankAtmGenEvcServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/ditsecws", "BankAtmGenEvcServicePort"), BankAtmGenEvcService.class, features);
    }

}
